#!/usr/bin/ruby

require 'date'
require 'digest/sha1'
require 'erubis'
require 'fileutils'
require 'ostruct'
require 'rubygems'
require 'rubygems/package'
require 'tmpdir'

#TODO: generate correct native depepdencies
#TODO: utilize 'aurb' + pacman (or something else) to get version of the package. So we avoid using versioned dependencies in depends=()
#TODO: build packages recursively (i.e. for depepdencies as well)
#TODO: implement 'update' mode. It should update existing PKGBUILD.

PKGBUILD = %{# Generated by gem2arch (https://github.com/anatol/gem2arch)
<% for m in maintainers %>
# Maintainer: <%= m %>
<% end %>
<% for c in contributors %>
# Contributor: <%= c %>
<% end %>

_gemname=<%= gem_name %>
pkgname=ruby-$_gemname
pkgver=<%= gem_ver %>
pkgrel=1
pkgdesc='<%= description %>'
arch=(<%= arch %>)
url='<%= website %>'
license=(<%= license %>)
depends=(<%= depends %>)
options=(!emptydirs)
source=("http://rubygems.org/downloads/$_gemname-$pkgver.gem")
noextract=("$_gemname-$pkgver.gem")
sha1sums=('<%= sha1sum %>')

package() {
  local _gemdir="$(ruby -e'puts Gem.default_dir')"
  gem install --ignore-dependencies --no-user-install -i "$pkgdir/$_gemdir" -n "$pkgdir/usr/bin" $_gemname-$pkgver.gem
  rm "$pkgdir/$_gemdir/cache/$_gemname-$pkgver.gem"
<% if license_file %>
  install -d "$pkgdir/usr/share/licenses/$pkgname/"
  install -m644 "$pkgdir/$_gemdir/gems/$_gemname-$pkgver/<%= license_file %>" "$pkgdir/usr/share/licenses/$pkgname/"
<% end %>
}
}

def download(gem_name, gem_version = nil)
  dependency = Gem::Dependency.new(gem_name, gem_version)
  found, _ = Gem::SpecFetcher.fetcher.spec_for_dependency(dependency)

  if found.empty? then
    $stderr.puts "Could not find #{gem_name} in any repository"
    exit 1
  end

  spec, source = found.sort_by{ |(s,_)| s.version }.last
  path = Gem::RemoteFetcher.fetcher.download(spec, source.uri.to_s)

  return path
end

def read_pkgbuild(file)
  pkgbuild = OpenStruct.new

  content = IO.read(file)
  pkgbuild.maintainers = content.scan(/# Maintainer: (.*)/).flatten
  pkgbuild.contributors = content.scan(/# Contributor: (.*)/).flatten

  return pkgbuild
end

def gen_pkgbuild(gem_path, existing_pkgbuild)
  gem = Gem::Package.new(gem_path)
  spec = gem.spec

  arch = spec.extensions.empty? ? 'any' : 'i686 x86_64'
  sha1sum = Digest::SHA1.file(gem_path).hexdigest

  depends = %w(ruby)
  depends += spec.runtime_dependencies.map{|d| 'ruby-' + d.name}

  licenses = spec.licenses.map{|l| l.index(' ') ? "'#{l}'" : l}

  # find files called COPYING or LICENSE in the root directory
  license_files = spec.files.dup.keep_if do |f|
    next false if f.index('/')
    next true if f.downcase.index('license')
    next true if f.downcase.index('copying')
    false
  end

  if license_files.size > 1 then
    $stderr.puts "There are several possible license files found in the gem: #{license_files}"
  end
  license_file = license_files[0] unless license_files.empty?


  if existing_pkgbuild
    maintainers = existing_pkgbuild.maintainers
    contributors = existing_pkgbuild.contributors
  else
    maintainers = []
    contributors = []
  end

  maintainers = [''] if  maintainers.empty? # Can we get the usename from somewhere? gitconfig?`

  params = {
    gem_name: spec.name,
    gem_ver: spec.version,
    website: spec.homepage,
    description: spec.summary,
    license: licenses.join(' '),
    arch: arch,
    sha1sum: sha1sum,
    depends: depends.join(' '),
    license_file: license_file,
    maintainers: maintainers,
    contributors: contributors
  }

  return Erubis::Eruby.new(PKGBUILD).result(params)
end

if $0 == __FILE__
  if ARGV.length < 1
    puts "Usage: #{$0} GEM_NAME [GEM_VER]"
    exit
  end

  gem_name = ARGV[0]
  gem_version = ARGV[1]

  gem_path = download(gem_name, gem_version)
  pkg_name = 'ruby-' + gem_name
  Dir.mkdir(pkg_name) unless File.exist?(pkg_name)
  puts "Generate PKGBUILD for #{pkg_name}"

  pkgbuild_file = File.join(pkg_name, 'PKGBUILD')
  existing_pkgbuild = read_pkgbuild(pkgbuild_file) if File.exist?(pkgbuild_file)
  IO.write(pkgbuild_file, gen_pkgbuild(gem_path, existing_pkgbuild))
end
